language: java

sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - OPENSHIFT_VERSIONS="v3.6.1"
    - OPENSHIFT_OC_VERSION="v3.6.1"
    - OPENSHIFT_OC_COMMIT_ID="008f2d5"

#before_install:
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#  - docker --version

before_script:
  - sudo mount --make-shared /
  - sudo service docker stop
  - sudo sed -i 's/DOCKER_OPTS=\"/DOCKER_OPTS=\"--insecure-registry 172.30.0.0\/16 /' /etc/default/docker
  - sudo service docker start
  - wget https://github.com/openshift/origin/releases/download/${OPENSHIFT_OC_VERSION}/openshift-origin-client-tools-${OPENSHIFT_OC_VERSION}-${OPENSHIFT_OC_COMMIT_ID}-linux-64bit.tar.gz
  - tar xvzOf openshift-origin-client-tools-${OPENSHIFT_OC_VERSION}-${OPENSHIFT_OC_COMMIT_ID}-linux-64bit.tar.gz > oc.bin
  - sudo mv oc.bin /usr/bin/oc
  - sudo chmod 755 /usr/bin/oc

script:
  - |
    oc cluster up --version=${version}
    oc login -u system:admin
    oc new-project scdf
    oc adm policy add-scc-to-user hostaccess -z default

    # run OpenShift deployer tests
    export KUBERNETES_NAMESPACE=scdf
    ./mvnw --batch-mode test \
      -Dspring.cloud.deployer.openshift.limits.memory=0Mi \
      -Dspring.cloud.deployer.openshift.limits.cpu=0m \
      -Dspring.cloud.deployer.openshift.livenessProbeDelay=20 \
      -Dspring.cloud.deployer.openshift.readinessProbeDelay=20

after_failure:
 - oc login -u system:admin
 - oc get all -n scdf -o yaml
 - oc get events --all-namespaces --sort-by='.metadata.creationTimestamp'

after_success:
  - |
    if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
      echo "Should we use this?"
    fi
